---

- name: Install nginx
  apt: name=nginx

- name: Install PHP
  apt: name={{item}}
  with_items: [ php5, php5-fpm ]

- name: Configure nginx
  template:
    src: default-site.j2
    dest: /etc/nginx/sites-available/{{item.domain}}
  with_items: "{{nginx_sites}}"
  notify: Restart nginx

- name: Disable nginx default site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/{{item.domain}}
    dest: /etc/nginx/sites-enabled/{{item.domain}}
    state: link
  with_items: "{{nginx_sites}}"
  notify: Restart nginx

- name: Create keys directory
  file:
    path: /etc/nginx/keys
    state: directory
    mode: 0700

- name: Create directory to install getssl in /opt
  file:
    path: /opt/getssl
    state: directory

- name: Create getssl directory
  file:
    path: /opt/getssl/{{ item.domain }}
    state: directory
    mode: 0700
  when: "{{ item.tls | default(false) }}"
  with_items: "{{nginx_sites}}"

- name: Create getssl configs
  template:
    src: getssl.cfg.j2
    dest: /opt/getssl/{{ item.domain }}/getssl.cfg
  when: "{{ item.tls | default(false) }}"
  with_items: "{{nginx_sites}}"

- name: Download getssl
  get_url:
    url: https://raw.githubusercontent.com/srvrco/getssl/cb7779102a96e4802249460255303babaf1d8322/getssl
    dest: /opt/getssl/getssl
    mode: 0700
    checksum: sha256:61d77e8d33915ac4026033091600628991463b55aadf367d8408efb933d4d613

- name: Run getssl
  command: /opt/getssl/getssl -w /opt/getssl -U {{ item.domain }}
  when: "{{ item.tls | default(false) }}"
  with_items: "{{nginx_sites}}"

- name: Add cron job for getssl
  template:
    src: getssl.cron.j2
    dest: /etc/cron.daily/getssl
    mode: 0755
