---

- name: Install nginx
  apt: name=nginx

- name: Install PHP
  apt: name={{item}}
  with_items: [ php5, php5-fpm ]

- name: Configure nginx
  template:
    src: default-site.j2
    dest: /etc/nginx/sites-available/{{item.domain}}
  with_items: "{{nginx_sites}}"
  notify: Restart nginx

- name: Delete nginx default site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/{{item.domain}}
    dest: /etc/nginx/sites-enabled/{{item.domain}}
    state: link
  with_items: "{{nginx_sites}}"
  notify: Restart nginx

- name: Create keys directory
  file:
    path: /etc/nginx/keys
    state: directory
    mode: 0700

- name: Generate private TLS key
  command: openssl genrsa -out /etc/nginx/keys/{{item.domain}}.key 4096
  with_items: "{{nginx_sites}}"

#- name: Generate public key
#  command: openssl rsa -in /etc/nginx/keys/{{item.domain}}.key -pubout -out /etc/nginx/keys/{{item.domain}}.pub
#  with_items: "{{nginx_sites}}"

- name: Generate CSR
  command: openssl req -new -sha512 -key /etc/nginx/keys/{{item.domain}}.key -out /etc/nginx/keys/{{item.domain}}.csr -subj "/C={{item.cert_country}}/L={{item.cert_location}}/O={{item.cert_organisation}}/CN={{item.domain}}"
  with_items: "{{nginx_sites}}"

#- name: Lets encrypt 0
#  letsencrypt:
#    account_key: /etc/nginx/keys/{{item.domain}}.key
#    account_key: /etc/nginx/keys/testfuerraute.ffh.zone.key
#    csr: /etc/nginx/keys/{{item.domain}}.csr
#    csr: /etc/nginx/keys/testfuerraute.ffh.zone.csr
#    dest: /etc/nginx/keys/{{item.domain}}.crt
#    dest: /etc/nginx/keys/testfuerraute.ffh.zone.crt
#  register: letsencrypt_challenge['testfuerraute.ffh.zone']
#  with_items: "{{nginx_sites}}"

#- name: Prepare http challenge
#  file:
#    path: "{{item.root}}/.well-known/acme-challenge"
#    state: directory
#    mode: 0755
#  with_items: "{{nginx_sites}}"

#- name: Solve letsencrypt challenge
#  copy:
#    dest: "{{item.root}}/{{ letsencrypt_challenge['testfuerraute.ffh.zone']['challenge_data']['testfuerraute.ffh.zone']['http-01']['resource'] }}"
#    content: "{{ letsencrypt_challenge['testfuerraute.ffh.zone']['challenge_data']['testfuerraute.ffh.zone']['http-01']['resource_value'] }}"
#  when: letsencrypt_challenge|changed
#  with_items: "{{nginx_sites}}"

#- name: Lets encrypt 1
#  letsencrypt:
#    account_key: /etc/nginx/keys/{{item.domain}}.key
#    csr: /etc/nginx/keys/{{item.domain}}.csr
#    dest: /etc/nginx/keys/{{item.domain}}.crt
#    data: "{{ letsencrypt_challenge }}"
#  with_items: "{{nginx_sites}}"
