---

- name: Create network interface for each gt endpoint
  notify: Restart networkd
  template:
    src: gt-network.j2
    dest: /etc/systemd/network/19-gt-{{ item.key }}.network
  when: item.key != servername
  with_dict: "{{ supernodes }}"

- name: Create /etc/systemd/network/10-eth0.network.d directory
  notify: Restart networkd
  file:
    name: /etc/systemd/network/10-eth0.network.d  
    state: directory

- name: Drop tunnel config into /etc/systemd/network/10-eth0.network.d directory
  notify: Restart networkd
  template: 
    src: gt-tunnel.conf.j2
    dest: /etc/systemd/network/10-eth0.network.d/gt-tunnel.conf

- name: Create gt tunnel in networkd
  notify: Restart networkd
  template:
    src: gt-netdev.j2
    dest: /etc/systemd/network/19-gt-{{ item.key }}.netdev
  when: item.key != servername
  with_dict: "{{ supernodes }}"

- name: Create gt bridge in networkd
  notify: Restart networkd
  template:
    src: br-gt-{{ item }}.j2
    dest: /etc/systemd/network/19-br-gt.{{ item }}
  with_items:
    - network
    - netdev

- name: Create vlan-gt* devices
  notify: Restart networkd
  template:
    src: vlan-gt-netdev.j2
    dest: /etc/systemd/network/19-vlan-gt-{{ 200 + (item.id | int) }}.netdev
  when: legacy_dom0
  with_items:
    - id: 0

- name: Create vlan-gt* devices
  notify: Restart networkd
  template:
    src: vlan-gt-netdev.j2
    dest: /etc/systemd/network/19-vlan-gt-{{ 200 + (item.id | int) }}.netdev
  with_items:
    - "{{ domains }}"

- name: Create vlan-gt* networks
  notify: Restart networkd
  template:
    src: vlan-gt-network.j2
    dest: /etc/systemd/network/19-vlan-gt-{{ 200 + (item.id | int) }}.network
  when: legacy_dom0
  with_items:
    - id: 0

- name: Create vlan-gt* networks
  notify: Restart networkd
  template:
    src: vlan-gt-network.j2
    dest: /etc/systemd/network/19-vlan-gt-{{ 200 + (item.id | int) }}.network
  with_items: "{{ domains }}"

- name: Create systemd service to add vlan-gt-200 devices into bat0
  template:
    src: addtobatX.j2
    dest: /etc/systemd/system/add-gt-to-bat{{ item.id }}.service
  when: legacy_dom0
  with_items:
    - id: 0

- name: Create systemd service to add vlan-gt* devices into bat*
  template:
    src: addtobatX.j2
    dest: /etc/systemd/system/add-gt-to-bat{{ item.id }}.service
  with_items:
    - "{{domains}}"

- name: Systemd daemon-reload
  command: systemctl daemon-reload

- name: Enable systemd services for dom0
  command: systemctl enable add-gt-to-bat{{ item.id }}.service
  when: legacy_dom0
  with_items:
    - id: 0

- name: Enable systemd services
  command: systemctl enable add-gt-to-bat{{ item.id }}.service
  with_items:
    - "{{ domains }}"

- name: Start systemd services for dom0
  command: systemctl start add-gt-to-bat{{ item.id }}.service
  when: legacy_dom0
  with_items:
    - id: 0

- name: Start systemd services
  command: systemctl start add-gt-to-bat{{ item.id }}.service
  with_items:
    - "{{ domains }}"

#- name: Generate firewall config stanza for GRE tunnel (ferm) TODO!!!!
#  notify: reload ferm
#  template:
#    src: ferm.gre.conf.j2
#    dest: /etc/ferm/conf.d/10-gre-exitnodes.conf


