---

- name: Adjust netfilter conntrack table size
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "{{ firewall_conntrack_table_size }}"
    state: "{% if firewall_conntrack_table_size != -1 %}present{% else %}absent{% endif %}"
    sysctl_file: /etc/sysctl.d/20-conntrack.conf
    reload: yes

- name: Maybe activate forwarding 4 as kernel parameter
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "1"
    sysctl_file: /etc/sysctl.d/50-forwarding.conf
    reload: yes

- name: Maybe activate forwarding 6 as kernel parameter
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_file: /etc/sysctl.d/50-forwarding.conf
    reload: yes

# icmp unreachable/... are correctly marked by this
- name: fwmark reflect IPv4
  sysctl:
    name: net.ipv4.fwmark_reflect
    value: 1
    sysctl_file: /etc/sysctl.d/50-fwmark-reflect.conf
    reload: yes

# icmp unreachable/... are correctly marked by this
- name: fwmark reflect IPv6
  sysctl:
    name: net.ipv6.fwmark_reflect
    value: 1
    sysctl_file: /etc/sysctl.d/50-fwmark-reflect.conf
    reload: yes

