---

- name: Install dependencies (git, sudo)
  apt: name={{ item }}
  with_items:
    - git
    - sudo

- name: Create auto user
  user:
    name: auto
    system: yes
    generate_ssh_key: yes

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/fastd_mesh/peers
    owner: auto

- name: Clone the peers git
  sudo: yes
  sudo_user: auto
  git:
    repo: "{{ git_addr }}:/peers"
    dest: /etc/fastd/fastd_mesh/peers

- name: Install autoupdate script
  template:
    dest: /home/auto/autoupdate_peers.sh
    src: autoupdate_peers.sh.j2
    owner: auto
    group: auto
    mode: "u=rwx,g=r,o=r"

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: /home/auto/autoupdate_peers.sh
