---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/fastd_mesh/peers
    owner: auto

- name: Clone the peers git
  become: yes
  become_user: auto
  git:
    repo: "{{ git_addr }}:/peers"
    dest: /etc/fastd/fastd_mesh/peers

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/fastd_mesh/peers
      && (systemctl reload fastd@ffh_mesh
      || echo "Reload of fastd_mesh instance failed")

- name: Enable peers-git remotes in fastd
  notify: Restart fastd_mesh
  blockinfile:
    dest: /etc/fastd/fastd_mesh/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
      peer group "peers-grp" {
        include peers from "peers";
      }
