---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/fastd_mesh/peers
    owner: auto

- name: Clone the peers git
  sudo: yes
  sudo_user: auto
  git:
    repo: "{{ git_addr }}:/peers"
    dest: /etc/fastd/fastd_mesh/peers

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/fastd_mesh/peers
      && (systemctl reload fastd@ffh_mesh
      || echo "Reload of fastd_mesh instance failed")
