---

- name: Install https for apt
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Add grafana repository key
  apt_key:
    url: https://packagecloud.io/gpg.key 
    state: present

- name: Add grafana repositories
  register: grafanarepo
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/testing/debian/ jessie main"

- name: Update apt chache to get grafana packages
  apt: update_cache=yes
  when: grafanarepo is changed

- name: Install grafana
  apt:
    name: grafana

- name: Generate grafana config
  notify: Restart grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Enable grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
