---
- name: Install isc-dhcp-server
  apt: name=isc-dhcp-server update_cache=yes

- name: Install dhcpd-pools
  apt: name=dhcpd-pools
  
- name: Ramdisk in fstab eintragen
  notify: Restart isc-dhcp-server
  mount: name=/var/lib/dhcp src=tmpfs fstype=tmpfs opts='defaults,size=100M' state=mounted

- name: Generate dhcpd master config
  notify: Restart isc-dhcp-server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: Generate dhcpd bat0 config
  notify: Restart isc-dhcp-server
  template:
    src: bat0.conf.j2
    dest: /etc/dhcp/bat0.conf
  when: legacy_dom0 == true

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain
  when: domains is defined

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-dhcpd.conf
  notify: reload ferm

- name: Deploy systemd service file
  template:
    src: dhcpd.service.j2
    dest: /etc/systemd/system/dhcpd.service

- name: Stop isc-dhcp-server via systemd
  systemd:
    name: isc-dhcp-server
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Disable isc-dhcp-server sysv scripts
  file:
    path: /etc/init.d/isc-dhcp-server
    state: absent

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable dhcpd
  command: systemctl enable dhcpd

- name: Start dhcpd
  command: systemctl start dhcpd
