- name: set variables
  set_fact:
    dhcp_net:
      net: "10.{{ domain.id }}.0.0"
      mask: "255.255.0.0"
    dhcp_interface: "bat{{ domain.id }}"
    dhcp_range:
      from: "10.{{ domain.id }}.{{ sn }}0.2"
      to: "10.{{ domain.id }}.{{ sn }}8.254"
    dhcp_options:
      dns_server: "10.{{ domain.id }}.0.1"
      gateway: "10.{{ domain.id }}.{{ sn }}0.1"

- name: "Generate dhcpd bat{{ domain.id }} config"
  notify: Restart isc-dhcp-server
  template:
    src: batX.conf.j2
    dest: "/etc/dhcp/bat{{ domain.id }}.conf"
