---

- hosts: aegidientor
  roles:
    - { name: ferm, tags: ferm }
    - { name: exitnode, tags: exitnode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: babeld, tags: babeld }
    - { name: ffnw, tags: ffnw }
    - { name: bird, tags: bird }
  vars_files:
    - vars/all_hosts.yml
  pre_tasks:
  vars:
    - servername: aegidientor
    - exitnode: 1
    - mail_fqdn: "aegidientor.e.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, mrplow, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 88.198.67.124/27
          - 2a01:4f8:140:430a::ff/64
        gateway4: 88.198.67.97
        gateway6: 2a01:4f8:140:430a::1
        dns_server: [213.133.98.98]
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests
          - 185.197.132.136/32 # ffnw ber
        static_routes:
          - dest: 185.197.132.136/32
            table: 23

    - babeld_interfaces: ["gre-sn01", "gre-sn02", "gre-sn03", "gre-sn04", "gre-sn05", "gre-sn06", "gre-sn07", "gre-sn08", "gre-sn09", "gre-sn10"]
