---

- hosts: bruehltor
  roles:
    - { name: ferm, tags: ferm }
    - { name: exitnode, tags: exitnode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: babeld, tags: babeld }

  vars_files:
    - vars/all_hosts.yml

  vars:
    - servername: bruehltor
    - en: 6
    - mail_fqdn: "bruehltor.e.ffh.zone"
    - admin_authorized: [lemoer, cawi, aiyion, jue, okrueger, raute, tobby, sush, codefetch]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 2a02:c207:3003:7339::1/64
          - 213.136.89.119/24
        gateway4: 213.136.89.1
        gateway6: fe80::1
        dns_server: ['9.9.9.10', '1.1.1.1', '2001:470:20::2']
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests

    - babeld_interfaces: ["gre-sn01", "gre-sn02", "gre-sn03", "gre-sn04", "gre-sn05", "gre-sn06", "gre-sn07", "gre-sn08", "gre-sn09", "gre-sn10"]
