---

- hosts: clevertor
  roles:
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_firewall, tags: simple_firewall }
    - { name: ssh_known_hosts, tags: ssh_known_hosts }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: misc, tags: misc }
  vars_files:
    - vars/all_hosts.yml
  pre_tasks:
    - include: sn_snippets/add_gre.yml
      vars:
        peer: sn01
      tags: always
  vars:
    - servername: clevertor
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush]
    - cron_apt_mailto: monitoring@hannover.freifunk.net

    - networkd_configures:
      - iface: eth0
        addresses:
          - 173.249.22.70/24
          - 2a02:c207:3002:4406::1/64
        gateway4: 173.249.22.1
        gateway6: fe80::1
        dns_server: [8.8.8.8]
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests

    - firewall_mssfix: 1330
    - firewall_open_ports_tcp: [1337]
    - firewall_allowed_forwards:
      - between: eth0
        and: gre-sn04

      - between: eth0
        and: gre-sn05

    - firewall_open_ports_tcp_by_ip:
      - port: 9100
        ip4: "{{ stats_address }}"

    - firewall_nat4_on_interfaces: ["eth0"]
    - firewall_conntrack_table_size: 1048576

    - reboot_on_kernelpanic: true
