---

- hosts: harvester
  roles:
    # General
    - { name: networkd, tags: networkd }
    - { name: ferm, tags: ferm }
    - { name: simple_mail, tags: simple_mail }
    - { name: admin, tags: admin }
    - { name: cli_tools, tags: cli_tools }
    - { name: cron-apt, tags: cron-apt }
    - { name: journald, tags: journald }
    # Batman
    - { name: mesh_batman, tags: mesh_batman }
    - { name: mesh_fastd, tags: mesh_fastd }
    - { name: mesh_fastd_remotes_backbone, tags: mesh_fastd_remotes_backbone }
    # Harvester
    - { name: influxdb, tags: influxdb }
    - { name: prometheus, tags: prometheus }
    - { name: node_exporter, tags: node_exporter }
    - { name: grafana, tags: grafana }
    - { name: yanic, tags: yanic }
    - { name: nginx, tags: nginx }

  vars_files:
      - vars/all_hosts.yml
      - vars/domains.yml
      - vars/secrets.yml

  vars:
    - servername: harvester
    - mail_fqdn: "harvester.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, bschelm, tobby, sush, codefetch, DarkAMD, s_2]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 88.198.66.29/27
          - 2a01:4f8:140:430a::101/64
        gateway4: 88.198.66.1
        gateway6: 2a01:4f8:140:430a::1
        dns_server: [213.133.99.99, 213.133.98.98, 213.133.100.100]

    - legacy_dom0: true
    - mesh_ula_address_suffix: 1231

    - yanic_port: 10002
    - yanic_nodes_enabled: true
    - yanic_nodes_path: /var/www/harvester.ffh.zone
    - yanic_influxdb_enabled: true
    - yanic_influx_database: yanic_harvester
    - yanic_influx_hostname: http://localhost:8086/
    # yanic_influx_password in var/secrets.yml

    - influxdb_meta_path: "/media/data/influxdb/meta"
    - influxdb_data_path: "/media/data/influxdb/data"
    - influxdb_wal_path:  "/media/data/influxdb/wal"
    - influxdb_bind_address: ":8086"
    - influxdb_clients:
        - "88.198.66.22/32"							# temp stats.ffh.zone
        - "2a01:4f8:140:430a::3001/128"	# temp stats.ffh.zone

    - prometheus_storage_path: "/media/data/prometheus"
    - prometheus_storage_retention: "8760h0m0s"
    - prometheus_clients:
        - "88.198.66.22/32"							# temp stats.ffh.zone
        - "2a01:4f8:140:430a::3001/128"	# temp stats.ffh.zone
    - prometheus_scrapes:
        - name: prometheus
          interval: 60
          timeout: 60
          targets: ['localhost:9090']
        - name: node_exporter
          interval: 60
          timeout: 30
          targets:
            - sn01.s.ffh.zone:9100
            - sn02.s.ffh.zone:9100
            - sn03.s.ffh.zone:9100
            - sn04.s.ffh.zone:9100
            - sn05.s.ffh.zone:9100
            - sn06.s.ffh.zone:9100
            - sn07.s.ffh.zone:9100
            - sn08.s.ffh.zone:9100
            - sn09.s.ffh.zone:9100
            - sn10.s.ffh.zone:9100
            - bruehltor.e.ffh.zone:9100
            - listertor.e.ffh.zone:9100
            - clevertor.e.ffh.zone:9100
            - leintor.e.ffh.zone:9100
            - aegidientor.e.ffh.zone:9100
            - harvester.ffh.zone:9100

    - grafana_datadir: "/media/data/grafana"
    - grafana_allow_signup: true
    - grafana_anonymous_access: true
    - grafana_smtp_host: "mail.ffh.zone:25"
    - grafana_smtp_from: "grafana@hannover.freifunk.net"

    - nginx_sites:
      - domain: harvester.ffh.zone
        root: /var/www/harvester.ffh.zone
        locations:
          - location: /
            allow_cors: true
            directory_index: true
            gzip: true
        tls: true
        tls_redirect_to_https: true
      - domain: opkg.ffh.zone
        tls: false
        locations:
          - location: /openwrt/
            type: proxy
            proxy_pass_host: false
            proxy_forward_url: http://downloads.openwrt.org/
          - location: /lede/
            type: proxy
            proxy_pass_host: false
            proxy_forward_url: http://archive.openwrt.org/
          - location: /modules/
            type: proxy
            proxy_pass_host: false
            proxy_forward_url: http://build.ffh.zone/job/gluon-beta/ws/beta/packages/
      - domain: prometheus.ffh.zone
        tls: true
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://[::1]:9090/
      - domain: stats.ffh.zone
        tls: true
        tls_redirect_to_https: true
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://localhost:3000/
