---

- hosts: harvester
  roles:
    # General
    - { name: networkd, tags: networkd }
    - { name: ferm, tags: ferm }
    - { name: simple_mail, tags: simple_mail }
    - { name: admin, tags: admin }
    - { name: cli_tools, tags: cli_tools }
    - { name: cron-apt, tags: cron-apt }
    - { name: journald, tags: journald }
    # Batman
    - { name: mesh_batman, tags: mesh_batman }
    - { name: mesh_fastd, tags: mesh_fastd }
    - { name: mesh_fastd_remotes_backbone, tags: mesh_fastd_remotes_backbone }
    # Harvester
    - { name: yanic, tags: yanic }
    - { name: nginx, tags: nginx }
    - { name: node_exporter, tags: node_exporter }

  vars_files:
      - vars/all_hosts.yml
      - vars/domains.yml
      - vars/secrets.yml

  vars:
    - servername: harvester
    - mail_fqdn: "harvester.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, bschelm, tobby, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 88.198.66.29/27
          - 2a01:4f8:140:430a::101/64
        gateway4: 88.198.66.1
        gateway6: 2a01:4f8:140:430a::1
        dns_server: [213.133.99.99, 213.133.98.98, 213.133.100.100]

    - legacy_dom0: true
    - mesh_ula_address_suffix: 1231

    - yanic_port: 10002
    - yanic_nodes_enabled: true
    - yanic_nodes_path: /var/www/harvester.ffh.zone
    - yanic_influxdb_enabled: true
    - yanic_influx_database: yanic_harvester
    - yanic_influx_hostname: http://sn03.s.ffh.zone:8086/
    # yanic_influx_password in var/secrets.yml

    - nginx_sites:
      - domain: harvester.ffh.zone
        root: /var/www/harvester.ffh.zone
        locations:
          - location: /
            allow_cors: true
            directory_index: true
            gzip: true
        tls: true
        tls_redirect_to_https: true
