---

- hosts: leintor
  roles:
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_firewall, tags: simple_firewall }
    - { name: ssh_known_hosts, tags: ssh_known_hosts }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: babeld, tags: babeld }
  vars_files:
    - vars/all_hosts.yml
  pre_tasks:
  vars:
    - servername: leintor
    - exitnode: 3
    - mail_fqdn: "leintor.e.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, mrplow, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 81.3.6.94/29
          - 2a02:790:1:ff::1001/64
        gateway4: 81.3.6.89
        gateway6: fe80::1
        dns_server: [81.3.3.81, 8.8.8.8]
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests
      - iface: eth1
        addresses:
          - 100.103.7.1/24
          - 100.103.8.1/24
          - 2a02:790:ff:100::1/64
        static_routes:
          - dest: 2a02:790:ff:8::/64
            gw: 2a02:790:ff:100::8
          - dest: 2a02:790:ff:7::/64
            gw: 2a02:790:ff:100::7
      - iface: gre-sn06
        addresses:
          - 100.103.6.1/24
          - 2a02:790:ff:106::1/64
        static_routes:
          - dest: 2a02:790:ff:6::/64
            gw: 2a02:790:ff:106::2
      - iface: gre-sn10
        addresses:
          - 100.103.10.1/24
          - 2a02:790:ff:110::1/64
        static_routes:
          - dest: 2a02:790:ff:10::/64
            gw: 2a02:790:ff:110::10

    - networkd_gre_tunnels:
      - name: gre-sn06
        lower_interface: eth0
        remote_outer_ip: 173.249.5.34
        local_outer_ip: 81.3.6.94
      - name: gre-sn10
        lower_interface: eth0
        remote_outer_ip: 173.212.248.190
        local_outer_ip: 81.3.6.94

    - firewall_mssfix: 1330
    - firewall_open_ports_tcp: [1337]

    - firewall_allowed_forwards: "all"

    - firewall_nat4_on_interfaces: ["eth0"]
    - firewall_conntrack_table_size: 1048576

    - firewall_open_ports_tcp_by_ip:
      - port: 9100
        ip4: "{{ stats_address }}"

    - babeld_interfaces: ["gre-sn01", "gre-sn02", "gre-sn03", "gre-sn04", "gre-sn05", "gre-sn06", "eth1", "gre-sn09", "gre-sn10"]
    - babeld_exitnode: true
