---

- hosts: listertor
  roles:
    - { name: ferm, tags: ferm }
    - { name: exitnode, tags: exitnode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: babeld, tags: babeld }
  vars_files:
    - vars/all_hosts.yml
  pre_tasks:
  vars:
    - servername: listertor
    - exitnode: 5
    - mail_fqdn: "listertor.e.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, mrplow, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 2a01:4f8:1c1c:2f89::1/64
        dhcp: true
        gateway6: fe80::1
        dns_server: [213.133.100.100, 8.8.8.8, 1.1.1.1]
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests

    - babeld_interfaces: ["gre-sn01", "gre-sn02", "gre-sn03", "gre-sn04", "gre-sn05", "gre-sn06", "gre-sn07", "gre-sn08", "gre-sn09", "gre-sn10"]
