---

- hosts: log
  roles:
    - { name: networkd, tags: networkd }
    - { name: ferm, tags: ferm }
    # admin stuff
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: cli_tools, tags: cli_tools }
    - { name: cron-apt, tags: cron-apt }
    # special
    - DavidWittman.redis

  vars_files:
    - vars/all_hosts.yml

  vars:
    - servername: log
    - mail_fqdn: "log.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, bschelm, tobby, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 88.198.66.30/27
          - 2a01:4f8:140:430a::112/64
        gateway4: 88.198.66.1
        gateway6: 2a01:4f8:140:430a::1
        dns_server: [213.133.98.98, 213.133.99.99]

    - redis_bind: 127.0.0.1
