---

- hosts: local-test-sn
  roles:
    - cli_tools
    - networkd
    - batman
    - ssh_known_hosts
    - fastd_mesh
    - fastd_mesh_remotes_backbone
    - fastd_mesh_remotes_peers_git
  vars:
    - networkd_uplink:
        interface: eth*
        networks:
          - addr: 10.0.2.15/24
            gateway: 10.0.2.2
        dns: 10.0.2.3

    - ip4_bat0: "10.2.150.1"
    - ip6_bat0: "fdca:ffee:8::9601"
    - fastd_mesh_mac: "88:E6:40:20:96:01"
    - git_addr: ssh://git@git.fnorden.net
