---

- hosts: local-test-sn
  roles:
    - cli_tools
    - networkd
    - ssh_known_hosts
    - mesh_batman
    - mesh_fastd
    - mesh_fastd_remotes_backbone
    - mesh_fastd_remotes_peers_git
  vars:
    - networkd_uplink:
        interface: eth*
        networks:
          - addr: 10.0.2.15/24
            gateway: 10.0.2.2
        dns: 10.0.2.3

    - ip4_bat0: "10.2.150.1"
    - ip6_bat0: "fdca:ffee:8::9601"
    - mesh_fastd_mac: "88:E6:40:20:96:01"
    - git_addr: ssh://git@git.fnorden.net

- hosts: gw03
  roles:
    - cli_tools
    - networkd
    - simple_firewall
    - ssh_known_hosts
    - mesh_batman
    - mesh_fastd
    - mesh_fastd_remotes_backbone
    - mesh_fastd_remotes_peers_git
    - radv_server
    - dns_recursive
    - dhcp_server
    - gateway_announcement
    - nginx
    - grafana
    - prometheus
    - stats_batches
  vars:
    - networkd_configures:
      - iface: eth0
        addresses:
          - 138.201.220.61/26
        gateway4: 138.201.220.1
        gateway6: fe80::1
        dns_server: [213.133.98.98]
      - iface: internetz-me
        addresses:
          - 192.168.43.31/31
          - fdca::1/64
      - iface: bat0
        addresses:
          - 10.2.30.1/16
          - fdca:ffee:8::1e01/64
          - fdca:ffee:8::108/64

    - networkd_gre_tunnels:
      - name: internetz-me
        lower_interface: eth0
        remote_outer_ip: 178.32.215.75
        local_outer_ip: 138.201.220.61

    - mesh_fastd_mac: "88:E6:40:20:1e:01"
    - git_addr: ssh://git@git.fnorden.net
    - firewall_open_ports_udp: [10000]
    - firewall_allowed_forwards:
      - between: bat0
        and: internetz-me
    - firewall_open_ports_tcp: [80, 443]

    - firewall_open_ports_udp_by_iface:
      - port: 53
        iface: bat0
      - port: 68
        iface: bat0
      - port: 9091
        iface: bat0

    - firewall_nat4_on_interfaces: ["internetz-me"]
    - firewall_conntrack_table_size: 1048576
    - firewall_alternative_routingtables:
      - name: freifunk
        when_packet_from: ["bat0", "internetz-me"]
        routes:
          - dest_net: default
            dest_if: internetz-me
            via: 192.168.43.30
          - dest_net: 10.2.0.0/16
            dest_if: bat0
          - dest_net: fdca:ffee:8::/64
            dest_if: bat0
    - dhcp_range:
        from: 10.2.30.2
        to: 10.2.39.254
    - dhcp_options:
        gateway: 10.2.30.1
        dns_server: 10.2.30.1

    - dns_recursive_allowed_nets:
      - 10.2.0.0/16
      - fdca:ffee:8::/48
    - dns_recursive_forwards:
      - zone: "."
        to: ["192.168.43.30"]
      - zone: "ffh.zone."
        to: ["fdca:ffee:8::1337"]
    - dns_recursive_allowed_private_adresses:
      - fdca:ffee:8::/48
    - dns_recursive_allowed_private_domains:
      - "ffh.zone."

    - radv_server_iface: "bat0"
    - radv_server_adv_prefixes:
      - fdca:ffee:8::/64
    - radv_server_adv_dns_servers:
      - fdca:ffee:8::1e01

    - nginx_sites:
      - domain: testfuerraute.ffh.zone
        root: /var/www
        tls: true
        ssl_cert_file: /dev/urandom
        ssl_key_file: /dev/urandom
        locations:
          - location: /karte
            type: files
          - location: /download
            type: files
            filesystem_path: /var/www/downloads
          - location: /forum
            type: fastcgi
            fcgi_socket: localhost:9090
      - domain: prometheus.ffh.zone
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://[::1]:9090/
      - domain: stats.ffh.zone
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://localhost:3000/

    - prometheus_scrapes:
        - name: prometheus
          interval: 60
          timeout: 60
          targets: ['localhost:9090']
        - name: pushgateway
          interval: 60
          timeout: 60
          targets: ['localhost:9091']
    - prometheus_use_pushgateway: true

    - grafana_allow_signup: true
    - grafana_anonymous_access: true

    - stats_pings:
      - host: 8.8.8.8
        name: google-dns
      - host: 192.168.43.30
        name: internetz-me

    - stats_fastd_sockets:
      - name: mesh_fastd
        path: /var/run/fastd.mesh_fastd.sock

    - stats_pushgateway:
        host: "[fdca:ffee:8::108]:9091"
        job: gw03

    - stats_bpfcountd_interfaces: ['bat0']


- hosts: gw02
  roles:
    - cli_tools
    - networkd
    - simple_firewall
    - ssh_known_hosts
    - mesh_batman
    - mesh_fastd
    - mesh_fastd_remotes_backbone
    - mesh_fastd_remotes_peers_git
    - radv_server
    - dns_recursive
    - dhcp_server
    - gateway_announcement
    - nginx
    - grafana
    - prometheus
    - stats_batches
  vars:
    - networkd_configures:
      - iface: eth0
        addresses:
          - 138.201.220.62/26
        gateway4: 138.201.220.1
        gateway6: fe80::1
        dns_server: [213.133.98.98]
      - iface: internetz-me
        addresses:
          - 192.168.43.21/31
          - fdca::1/64
      - iface: bat0
        addresses:
          - 10.2.20.1/16
          - fdca:ffee:8::1401/64

    - networkd_gre_tunnels:
      - name: internetz-me
        lower_interface: eth0
        remote_outer_ip: 178.32.215.75
        local_outer_ip: 138.201.220.62

    - mesh_fastd_mac: "88:E6:40:20:14:01"
    - git_addr: ssh://git@git.fnorden.net
    - firewall_open_ports_udp: [10000]
    - firewall_allowed_forwards:
      - between: bat0
        and: internetz-me
    - firewall_open_ports_tcp: [80, 443]

    - firewall_open_ports_udp_by_iface:
      - port: 53
        iface: bat0
      - port: 68
        iface: bat0
      - port: 9091
        iface: bat0

    - firewall_nat4_on_interfaces: ["internetz-me"]
    - firewall_conntrack_table_size: 1048576
    - firewall_alternative_routingtables:
      - name: freifunk
        when_packet_from: ["bat0", "internetz-me"]
        routes:
          - dest_net: default
            dest_if: internetz-me
            via: 192.168.43.20
          - dest_net: 10.2.0.0/16
            dest_if: bat0
          - dest_net: fdca:ffee:8::/64
            dest_if: bat0
    - dhcp_range:
        from: 10.2.20.2
        to: 10.2.29.254
    - dhcp_options:
        gateway: 10.2.20.1
        dns_server: 10.2.20.1

    - dns_recursive_allowed_nets:
      - 10.2.0.0/16
      - fdca:ffee:8::/48
    - dns_recursive_forwards:
      - zone: "."
        to: ["192.168.43.20"]
      - zone: "ffh.zone."
        to: ["fdca:ffee:8::1337"]
    - dns_recursive_allowed_private_adresses:
      - fdca:ffee:8::/48
    - dns_recursive_allowed_private_domains:
      - "ffh.zone."

    - radv_server_iface: "bat0"
    - radv_server_adv_prefixes:
      - fdca:ffee:8::/64
    - radv_server_adv_dns_servers:
      - fdca:ffee:8::1401

    - nginx_sites:
      - domain: testfuerraute.ffh.zone
        root: /var/www
        tls: true
        ssl_cert_file: /dev/urandom
        ssl_key_file: /dev/urandom
        locations:
          - location: /karte
            type: files
          - location: /download
            type: files
            filesystem_path: /var/www/downloads
          - location: /forum
            type: fastcgi
            fcgi_socket: localhost:9090
      - domain: prometheus.ffh.zone
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://[::1]:9090/
      - domain: stats.ffh.zone
        locations:
          - location: /
            type: proxy
            proxy_forward_url: http://localhost:3000/

    - prometheus_scrapes:
        - name: prometheus
          interval: 60
          timeout: 60
          targets: ['localhost:9090']
        - name: pushgateway
          interval: 60
          timeout: 60
          targets: ['localhost:9091']
    - prometheus_use_pushgateway: true

    - grafana_allow_signup: true
    - grafana_anonymous_access: true

    - stats_pings:
      - host: 8.8.8.8
        name: google-dns
      - host: 192.168.43.20
        name: internetz-me

    - stats_fastd_sockets:
      - name: mesh_fastd
        path: /var/run/fastd.mesh_fastd.sock

    - stats_pushgateway:
        host: "[fdca:ffee:8::108]:9091"
        job: gw03

    - stats_bpfcountd_interfaces: ['bat0']
