---

- hosts: local-test-sn
  roles:
    - cli_tools
    - networkd
    - batman
    - ssh_known_hosts
    - fastd_mesh
    - fastd_mesh_remotes_backbone
    - fastd_mesh_remotes_peers_git
  vars:
    - networkd_uplink:
        interface: eth*
        networks:
          - addr: 172.16.0.5/12
            gateway: 172.16.0.1
          - addr: fd34:fe56:7891:2f3a::223/64
            gateway: fd34:fe56:7891:2f3a::1
        dns: 8.8.8.8

    - ip4_bat0: "10.2.150.1"
    - ip6_bat0: "fdca:ffee:8::9601"
    - fastd_mesh_mac: "88:E6:40:20:96:01"
    - git_addr: ssh://git@git.fnorden.net
  vars_files:
    - secrets/local-test-sn.yml
