---

- hosts: sn02
  roles:
    - { name: ferm, tags: ferm }
    - { name: supernode, tags: supernode }
    - { name: networkd, tags: networkd }
    # - { name: reboot, tags: reboot }
    - { name: ssh_known_hosts, tags: ssh_known_hosts }
    - { name: mesh_batman, tags: mesh_batman }
    - { name: mesh_fastd, tags: mesh_fastd }
    - { name: mesh_fastd_remotes_backbone, tags: mesh_fastd_remotes_backbone }
    - { name: mesh_fastd_remotes_peers_git, tags: mesh_fastd_remotes_peers_git }
    - { name: radv_server, tags: radv_server }
    - { name: dns_recursive, tags: dns_recursive }
    - { name: dhcp_server, tags: dhcp_server }
    - { name: gateway_announcement, tags: gateway_announcement }
    - { name: stats_batches, tags: stats_batches }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: iperf3, tags: iperf3 }
    - { name: mesh_announce, tags: mesh_announce }
    - { name: cron-apt, tags: cron-apt }
    - { name: cli_tools, tags: cli_tools }
    - { name: node_exporter, tags: node_exporter }
    - { name: babeld, tags: babeld }
  vars_files:
    - vars/all_hosts.yml
    - vars/domains.yml
    - vars/secrets.yml
  vars:
    - servername: sn02
    - sn: 2
    - mail_fqdn: "sn02.s.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush]
    - cron_apt_mailto: monitoring@hannover.freifunk.net

    - legacy_dom0: true

    - networkd_configures:
      - iface: eth0
        addresses:
          - 2a01:4f8:1c0c:7149::2001/64
        dhcp: true
        gateway6: fe80::1
        dns_server: [213.133.98.98, 8.8.8.8]

    - stats_pings:
      - host: 8.8.8.8
        name: google-dns
      - host: 100.101.2.1
        name: internetz-me

    - babeld_interfaces: ['gre-aegidientor']
