---

- hosts: sn02
  roles:
    # General
    - { name: ferm, tags: ferm }
    - { name: supernode, tags: supernode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: reboot, tags: reboot }  # Enable reboot role on initial roleout.
    - { name: babeld, tags: babeld }
    - { name: simple_mail, tags: simple_mail }
    - { name: admin, tags: admin }
    - { name: cron-apt, tags: cron-apt }
    # Batman
    - { name: mesh_batman, tags: mesh_batman }
    - { name: mesh_fastd, tags: mesh_fastd }
    - { name: mesh_fastd_remotes_backbone, tags: mesh_fastd_remotes_backbone }
    - { name: mesh_fastd_remotes_peers_git, tags: mesh_fastd_remotes_peers_git }
    - { name: mesh_announce, tags: mesh_announce }
    # Stats, Monitoring, Logging
    - { name: radv_server, tags: radv_server }
    - { name: dns_recursive, tags: dns_recursive }
    - { name: dhcp_server, tags: dhcp_server }
    - { name: gateway_announcement, tags: gateway_announcement }
    - { name: node_exporter, tags: node_exporter }
    - { name: iperf3, tags: iperf3 }
    - { name: journald, tags: journald }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: reboot, tags: reboot }  # Enable reboot role on initial roleout.

  vars_files:
    - vars/all_hosts.yml
    - vars/domains.yml
    - vars/secrets.yml

  vars:
    - servername: sn02
    - sn: 2
    - mail_fqdn: "sn02.s.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush, codefetch, DarkAMD]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 2a01:4f8:1c0c:7149::2001/64
        dhcp: true
        gateway6: fe80::1
        no_radv_accept: true
        dns_server: [213.133.98.98, 8.8.8.8]

    - babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor', 'gre-aegidientor', 'gre-bruehltor']
    - babeld_interface_penalty:
        gre-aegidientor: 666
        gre-steintor: 666
        gre-leintor: 110
        gre-clevertor: 120
        gre-listertor: 666
        gre-bruehltor: 100

    - legacy_dom0: true
    - radv_announce_default: false
