---

- hosts: sn03
  roles:
    # General
    - { name: ferm, tags: ferm }
    - { name: supernode, tags: supernode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: reboot, tags: reboot }  # Enable reboot role on initial roleout.
    - { name: babeld, tags: babeld }
    - { name: simple_mail, tags: simple_mail }
    - { name: admin, tags: admin }
    - { name: cron-apt, tags: cron-apt }
    # Batman
    - { name: mesh_batman, tags: mesh_batman }
    - { name: mesh_fastd, tags: mesh_fastd }
    - { name: mesh_fastd_remotes_backbone, tags: mesh_fastd_remotes_backbone }
    - { name: mesh_fastd_remotes_peers_git, tags: mesh_fastd_remotes_peers_git }
    - { name: mesh_announce, tags: mesh_announce }
    # Stats, Monitoring, Logging
    - { name: radv_server, tags: radv_server }
    - { name: dns_recursive, tags: dns_recursive }
    - { name: dhcp_server, tags: dhcp_server }
    - { name: gateway_announcement, tags: gateway_announcement }
    - { name: node_exporter, tags: node_exporter }
    - { name: iperf3, tags: iperf3 }
    - { name: journald, tags: journald }
    - { name: reboot, tags: reboot }  # Enable reboot role on initial roleout.

  vars_files:
    - vars/all_hosts.yml
    - vars/domains.yml
    - vars/secrets.yml

  vars:
    - servername: sn03
    - sn: 3
    - mail_fqdn: "sn03.s.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 89.163.209.226/24
          - 2001:4ba0:babe:3054::3001/64
        gateway4: 89.163.209.1
        gateway6: 2001:4ba0:babe::1
        no_radv_accept: true
        dns_server: [62.141.32.4, 9.9.9.10]

    - babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor']
    - babeld_interface_penalty:
        gre-listertor: 100
        gre-steintor: 110
        gre-clevertor: 120
        gre-leintor: 130

    - legacy_dom0: true
    - radv_announce_default: false
