---

- hosts: steintor
  roles:
    - { name: ferm, tags: ferm }
    - { name: exitnode, tags: exitnode }
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
    - { name: node_exporter, tags: node_exporter }
    - { name: cron-apt, tags: cron-apt }
    - { name: babeld, tags: babeld }

  vars_files:
    - vars/all_hosts.yml

  vars:
    - servername: steintor
    - exitnode: 2
    - mail_fqdn: "steintor.e.ffh.zone"
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush]

    - networkd_configures:
      - iface: eth0
        addresses:
          - 37.120.190.215/22
          - 2a03:4000:6:b1d6::1/64
        gateway4: 37.120.188.1
        gateway6: fe80::1
        dns_server: ['2a03:4000:0:1::e1e6', '46.38.252.230', '1.1.1.1']
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests

    - babeld_interfaces: ["gre-sn01", "gre-sn02", "gre-sn03", "gre-sn04", "gre-sn05", "gre-sn06", "gre-sn07", "gre-sn08", "gre-sn09", "gre-sn10"]
