---

- hosts: steintor
  roles:
    - { name: cli_tools, tags: cli_tools }
    - { name: networkd, tags: networkd }
    - { name: simple_firewall, tags: simple_firewall }
    - { name: ssh_known_hosts, tags: ssh_known_hosts }
    - { name: simple_mail, tags: simple_mail }
    - { name: journald, tags: journald }
    - { name: admin, tags: admin }
  vars_files:
    - vars/all_hosts.yml
  vars:
    - admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush]
    - networkd_configures:
      - iface: eth0
        addresses:
          - 37.120.190.215/22
          - 2a03:4000:6:b1d6::1/64
        gateway4: 37.120.188.1
        gateway6: fe80::1
        dns_server: [8.8.8.8]
      - iface: lo
        addresses:
          - 100.100.0.1/32 # anycast for ping tests
      - iface: gre-sn04
        addresses:
          - 192.168.44.42/30
      - iface: gre-sn05
        addresses:
          - 192.168.44.49/30

    - networkd_gre_tunnels:
      - name: gre-sn04
        lower_interface: eth0
        remote_outer_ip: 46.38.253.239
        local_outer_ip: 37.120.190.215

      - name: gre-sn05
        lower_interface: eth0
        remote_outer_ip: 5.45.103.36
        local_outer_ip: 37.120.190.215

    - firewall_mssfix: 1330
    - firewall_open_ports_tcp: [1337]
    - firewall_allowed_forwards:
      - between: eth0
        and: gre-sn04

      - between: eth0
        and: gre-sn05

    - firewall_nat4_on_interfaces: ["eth0"]
    - firewall_conntrack_table_size: 1048576
