---

- name: Restart mesh_fastd
  service: name=fastd@mesh_fastd state=restarted

- name: Restart domain fastds
  service: name=fastd@mesh_fastd_{{ domain.id }} state=restarted
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain
  when: domains is defined
