---

- name: Install dependencies
  apt: name={{ item }}
  with_items: ["git", "curl", "netcat-openbsd"]

- name: Create auto user
  register: createuser
  user:
    name: auto
    system: yes

- name: Create stats scripts directory
  file:
    path: "{{ stats_batch_install_path }}/handler"
    state: directory


- name: Install the shell scripts
  copy:
    src: handler/
    dest: "{{ stats_batch_install_path }}/handler/"

- name: Generate custom gen_stats.sh script
  template:
    src: stats.sh.j2
    dest: "{{ stats_batch_install_path }}/gen_stats.sh"
    mode: "0755"

- name: Automatically push stats
  cron:
    name: "push stats"
    user: auto
    minute: "*"
    job: >
      sh {{ stats_batch_install_path }}/gen_stats.sh |
      curl -s -X POST --data-binary @-
      {{ stats_pushgateway.host }}/metrics/job/{{ servername }}

- name: Install bpfcountd stuff
  include_tasks: bpfcountd.yml
