---
- name: "Uninstall Debian's babeld"
  apt: 
    name: "babeld"
    state: "absent"

- name: "Add build dependencies"
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential

- name: "Clone babeld git repo"
  git:
    repo: "https://github.com/jech/babeld.git"
    dest: "/usr/src/babeld-{{ babeld_build_version }}/"
    version: "{{ babeld_build_version }}"

- name: "Make babeld"
  register: "babeldmake"
  make:
    chdir: "/usr/src/babeld-{{ babeld_build_version }}"

- name: "Install babeld"
  notify: "Restart babeld"
  command: "cp /usr/src/babeld-{{ babeld_build_version }}/babeld /usr/sbin/babeld"
  when: babeldmake is changed

- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Save built version"
  copy:
    content: '"{{babeld_build_version}}"'
    dest: "/etc/ansible/facts.d/babeld_built_version.fact"
