---

- name: Build from source
  when: babeld_build_from_source
  block:
    - name: Uninstall babeld
      apt: name=babeld state=absent

    - name: Include 'Build from source'
      include_tasks: build_from_source.yml
      when: (ansible_local['babeld_built_version'] | default(None)) != babeld_build_version

- name: Configure system correctly (once)
  when: not (ansible_local['babeld_system_configured'] | default(False))
  include_tasks: configure.yml

- name: Install babeld supernode config
  notify: Restart babeld
  template:
    src: supernode.conf.j2
    dest: /etc/babeld.conf
  when: sn is defined

- name: Install babeld exitnode config
  notify: Restart babeld
  template:
    src: exitnode.conf.j2
    dest: /etc/babeld.conf
  when: en is defined

