---

- name: Install ferm
  apt: 
    name: ferm

- name: Prepare ferm conf.d directory
  file:
    path: /etc/ferm/conf.d
    state: directory
    mode: 0755

- name: Set /etc/default/ferm
  template:
    src: default
    dest: /etc/default/ferm

- name: Install main configuration file
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
  notify: reload ferm

- name: ferm config for final REJECTs
  template:
    src: 99-REJECT.conf
    dest: /etc/ferm/conf.d/99-REJECT.conf
  notify: reload ferm

- name: Enable ferm service
  service:
    name: ferm
    enabled: yes
    state: started

