---

- name: Install ferm
  apt: 
    name: ferm

- name: Prepare ferm conf.d directory
  file:
    path: /etc/ferm/conf.d
    state: directory
    mode: 0755

- name: Set /etc/default/ferm
  copy:
    src: files/default
    dest: /etc/default/ferm

- name: Install main configuration file
  copy:
    src: files/ferm.conf
    dest: /etc/ferm/ferm.conf

- name: ferm config for final REJECTs
  copy:
    src: files/99-REJECT.conf
    dest: /etc/ferm/conf.d/99-REJECT.conf

- name: Enable ferm service
  service:
    name: ferm
    enabled: no
    state: stopped

