---

- name: Install unbound
  apt: name=unbound

- name: Configure unbound
  notify: Restart unbound
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf

- name: Install unbound service file
  template:
    src: unbound.service.j2
    dest: /etc/systemd/system/unbound.service

- name: Remove legacy init.d file
  file:
    path: /etc/init.d/unbound
    state: absent

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-unbound.conf
  notify: reload ferm

- name: Enable unbound
  command: systemctl enable unbound
