---

- name: Install Foswiki dependencies
  apt: name={{ item }}
  with_items:
    - tar
    - unzip
    - perl
    - libalgorithm-diff-perl
    - libauthen-sasl-perl
    - libcgi-pm-perl
    - libcgi-session-perl
    - libcrypt-passwdmd5-perl
    - libdigest-sha-perl
    - libemail-mime-perl
    - libencode-perl
    - liberror-perl
    - libfile-copy-recursive-perl
    - libhtml-parser-perl
    - libhtml-tree-perl
    - libio-socket-ip-perl
    - libio-socket-ssl-perl
    - libjson-perl
    - liblocale-maketext-lexicon-perl
    - liblocale-msgfmt-perl
    - libwww-perl
    - liblwp-protocol-https-perl
    - liburi-perl
    - libversion-perl

- name: Prepare Foswiki directory
  file:
    path: /var/www/foswiki
    state: directory
    mode: 0755

- name: Check if Foswiki is already there
  stat:
    path: /var/www/foswiki/readme.txt
  register: foswiki_st

- name: Install Foswiki package
  unarchive:
    src: https://github.com/foswiki/distro/releases/download/FoswikiRelease02x01x04/Foswiki-2.1.4.tgz
    dest: /var/www/foswiki
    remote_src: True
    extra_opts: ['--strip-components=1']
  when: not foswiki_st.stat.exists

- name: Install SystemD unit file
  copy:
    src: /var/www/foswiki/tools/systemd/foswiki.service
    dest: /etc/systemd/system/
    remote_src: yes
