- name: Restart domain tunneldiggers
  service: name=tunneldigger state=restarted
  when: domains is defined and sn is defined

- name: Load kernel modules
  shell: /etc/init.d/kmod start || true
  when: domains is defined and sn is defined
