---

- name: Install dependencies (git, sudo)
  apt: name={{ item }} update_cache=yes
  with_items:
    - git
    - sudo

- name: Create auto user
  register: createuser
  user:
    name: auto
    system: yes
    generate_ssh_key: yes

- name: Publish new public ssh key to repository
  include_tasks: gitolite.yml
  when: createuser|changed

#- name: Create lockfile to wait until ssh key is deployed to the git server
#  file: path=/home/auto/wait_for_access.lock state=touch
#  when: createuser|changed

#- name: Wait until the ssh key is deployed to the git server and lockfile is removed manually
#  wait_for: path=/home/auto/wait_for_access.lock state=absent

- name: Install autoupdate script
  template:
    dest: /home/auto/autoupdate.sh
    src: autoupdate.sh.j2
    owner: auto
    group: auto
    mode: "u=rwx,g=r,o=r"

- name: Install global ssh known_hosts file
  template:
    src: known_hosts.j2
    dest: /etc/ssh/ssh_known_hosts
