---

- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  blockinfile:
    dest: /etc/fastd/mesh_fastd/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
     peer group "peers-grp" {
        include peers from "peers";
      }

- name: Generate peers symlink
  file:
    src: "/etc/fastd/peers"
    dest: "/etc/fastd/mesh_fastd/peers"
    state: link

