---

- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  template:
    src: "remotes.conf.j2"
    dest: /etc/fastd/mesh_fastd/remotes.conf
    mode: "0644"

- name: Generate peers symlink
  file:
    src: "/etc/fastd/peers"
    dest: "/etc/fastd/mesh_fastd/peers"
    state: link

