---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/peers
    owner: auto

- name: Create the peers' activity directory
  file:
    state: directory
    dest: /var/fastd_peers
    owner: auto

- name: Clone the peers git
  become: yes
  become_user: auto
  git:
    repo: "{{ git_addr }}/peers"
    dest: /etc/fastd/peers
    accept_hostkey: true

- name: Allow restarting the fastd instance for user auto
  template:
    src: user-auto-reload-fastd
    dest: /etc/sudoers.d/user-auto-reload-fastd

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/peers
      && (sudo /usr/bin/killall -HUP fastd
      || echo "Reload of mesh_fastd instance failed")

- name: Install crontab for peer activity monitoring
  cron:
    name: "saves last access time of a peer"
    user: auto
    minute: "23"
    hour: "*/11"
    job: |
      /bin/bash -c ' \
      for i in $(for j in $(for k in /var/run/*.sock; \
                                do echo $k; \
                            done | grep "/var/run/fastd";); \
                     do nc -U "$j" | jq -r ".peers[] | select(.connection != null) | .name"; \
                 done;); \
          do touch "/var/fastd_peers/$i"; \
      done;'

- name: dom0 peers config
  include_tasks: dom0.yml
  when: legacy_dom0 == true

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined
