---
- name: Install radvd
  apt: name=radvd update_cache=yes

- name: Generate radvd config
  notify: Restart radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf

- name: Add systemd service file
  template:
    src: systemd.service
    dest: /etc/systemd/system/radvd.service
    # Remove this when debian gets a real service file

- name: Enable radvd
  command: systemctl enable radvd

- name: Start radvd
  command: systemctl start radvd
