---

- name: Add build dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - dkms
    - git
    - linux-headers-amd64

- name: Clone batman sources
  git:
    repo: https://git.open-mesh.org/batman-adv.git
    dest: /usr/src/batman-adv-{{ batman_build_version }}/
    version: "{{ batman_build_version }}"

- name: Remove from dkms
  command: dkms remove batman-adv/{{ batman_build_version }} --all
  # TODO: conditionalize, only if there is sth to remove

- name: Reset batman
  command: git -C /usr/src/batman-adv-{{ batman_build_version }}/ reset --hard {{ batman_build_version }}

- name: Patch batman
  shell: curl {{ item }} | git -C /usr/src/batman-adv-{{ batman_build_version }}/ am
  with_items:
   - https://paste.irrelefant.net/einei4aN.txt
   - https://paste.irrelefant.net/xoraza8E.txt
   - https://patchwork.open-mesh.org/patch/17405/mbox/ # crc issue
   - https://patchwork.open-mesh.org/patch/17406/mbox/ # crc issue
   - https://paste.irrelefant.net/chieNoo8.txt # crc issue counters

- name: Add the dkms info to the source
  template:
    src: dkms.conf.j2
    dest: /usr/src/batman-adv-{{ batman_build_version }}/dkms.conf

- name: Get dkms status
  register: dkmsstatus
  command: "dkms status"
  changed_when: false

- name: Get dkms status for version {{ batman_build_version }}
  set_fact: batman_version_status="{{ dkmsstatus.stdout_lines | select('match', '^batman-adv, ' + batman_build_version) | first | default("noversion") }}"
  # " (hotfix for vi's syntax highlighting)

- debug: var=batman_version_status

- name: Add version {{ batman_build_version }} to dkms
  command: "dkms add -m batman-adv -v {{ batman_build_version }}"
  when: 'noversion' in batman_version_status

- name: Install version {{ batman_build_version }} using dkms
  register: installedversion
  command: "dkms install --force -m batman-adv -v {{ batman_build_version }}"
  when: 'installed' not in batman_version_status

- name: Unload batman_adv module when installed version has changed
  # The module will be loaded by "Load batman_adv module" again
  modprobe: name=batman_adv state=absent
  when: installedversion is changed
