---

- name: Reboot
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for port 1337 to become open and contain "OpenSSH"
  wait_for:
    port: 1337
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 30
  connection: local
  ignore_errors: yes

- name: Re-gather facts since some things could have changed
  setup:
    filter: "*"
