---

- name: Install fastd
  include_tasks: install.yml

- name: Generate secret if necessary
  include_tasks: secret.yml

- name: Set network buffers
  include_tasks: buffers.yml

- name: Generate config for dom0
  include_tasks: dom0.yml
  when: legacy_dom0 == true

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined

- name: Reread networkd config for new bat devices
  systemd:
    name: systemd-networkd
    state: restarted

- name: Firewalling mesh_fastd for all domains
  include_tasks: ferm.yml

