---

- name: Check if secret.conf exists
  register: secretfile
  stat: path=/etc/fastd/secret.conf

- name: Generate secret
  register: generatedsecret
  command: fastd --generate-key --machine-readable
  when: not secretfile.stat.exists

- name: Install mesh_fastd daemon secret
  notify: Restart mesh_fastd
  when: not secretfile.stat.exists
  template:
    dest: "/etc/fastd/secret.conf"
    src: "secret.conf.j2"
    mode: "u=rw,g=,o="

