---

- name: Install tunneldigger
  include_tasks: install_tunneldigger.yml
  when: domains is defined and sn is defined

- name: Setup L2TP bridges
  include_tasks: l2tp_bridges.yml
  when: domains is defined and sn is defined

- name: Enable all tunneldigger instances
  systemd:
    name: tunneldigger
    enabled: yes
  when: domains is defined and sn is defined

- name: Deploy tunneldigger.cfg
  template: src="tunneldigger.cfg.j2" dest="/srv/tunneldigger/conf/tunneldigger.cfg"
  notify: Restart tunneldigger
  when: domains is defined and sn is defined

- name: Open up ports for L2TP
  notify: reload ferm
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-mesh_l2tp.conf
  when: domains is defined and sn is defined
