---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/mesh_fastd/peers
    owner: auto

- name: Clone the peers git
  become: yes
  become_user: auto
  git:
    repo: "{{ git_addr }}:1337/peers"
    dest: /etc/fastd/mesh_fastd/peers
    accept_hostkey: true

- name: Allow restarting the fastd instance for user auto
  template:
    src: user-auto-reload-fastd
    dest: /etc/sudoers.d/user-auto-reload-fastd

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/mesh_fastd/peers
      && (sudo /usr/bin/killall -HUP fastd
      || echo "Reload of mesh_fastd instance failed")

- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  blockinfile:
    dest: /etc/fastd/mesh_fastd/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
     peer group "peers-grp" {
        {% if mesh_fastd_peer_limit is defined %}
        peer limit {{ mesh_fastd_peer_limit }};
        {% endif %}
        include peers from "peers";
      }

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined
