---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/mesh_fastd/peers
    owner: auto

- name: Clone the peers git
  become: yes
  become_user: auto
  git:
    repo: "{{ git_addr }}:/peers"
    dest: /etc/fastd/mesh_fastd/peers

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/mesh_fastd/peers
      && (systemctl reload fastd@mesh_fastd
      || echo "Reload of mesh_fastd instance failed")

- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  blockinfile:
    dest: /etc/fastd/mesh_fastd/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
      peer group "peers-grp" {
        include peers from "peers";
      }
