---

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/fastd/mesh_fastd/peers
    owner: auto

- name: Clone the peers git
  become: yes
  become_user: auto
  git:
    repo: "{{ git_addr }}:/peers"
    dest: /etc/fastd/mesh_fastd/peers
    accept_hostkey: true

- name: Allow restarting the fastd instance for user auto
  template:
    src: user-auto-reload-fastd
    dest: /etc/sudoers.d/user-auto-reload-fastd

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate peers from git"
    user: auto
    minute: "*/5"
    job: >
      /home/auto/autoupdate.sh
      /etc/fastd/mesh_fastd/peers
      && (sudo systemctl reload fastd@mesh_fastd
      || echo "Reload of mesh_fastd instance failed")

- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  blockinfile:
    dest: /etc/fastd/mesh_fastd/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
      {% if mesh_fastd_deny_connections_over_mbit_integer is defined %}
      on verify "/etc/fastd/mesh_fastd/on_verify.sh";
      {% endif %}
      peer group "peers-grp" {
        {% if mesh_fastd_peer_limit is defined %}
        peer limit {{ mesh_fastd_peer_limit }};
        {% endif %}
        {% if mesh_fastd_deny_connections_over_mbit_integer is not defined %}
        include peers from "peers";
        {% endif %}
      }

- name: Install on verfiy_script
  template:
    src: on_verify.sh.j2
    dest: /etc/fastd/mesh_fastd/on_verify.sh
    mode: 755
  when: mesh_fastd_deny_connections_over_mbit_integer is defined

- name: Install bandwidth test script
  template:
    src: traffic.sh.j2
    dest: /etc/fastd/mesh_fastd/traffic.sh
    mode: 755

- name: Install cronjob for bandwidth test scripts
  cron:
    name: "generate traffic statistic for fastd foobar"
    minute: "*/5"
    user: root
    job: /etc/fastd/mesh_fastd/traffic.sh 300

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined
