- name: Enable peers-git remotes in fastd
  notify: Restart mesh_fastd
  blockinfile:
    dest: /etc/fastd/mesh_fastd_{{ domain.id }}/remotes.conf
    marker: "# {mark} PEERS GIT (ANSIBLE)"
    content: |
     peer group "peers-grp" {
        {% if mesh_fastd_peer_limit is defined %}
        peer limit {{ mesh_fastd_peer_limit }};
        {% endif %}
        include peers from "peers";
      }

- name: Generate peers symlink
  file:
    src: "/etc/fastd/mesh_fastd/peers"
    dest: "/etc/fastd/mesh_fastd_{{ domain.id }}/peers"
    state: link
