---

- name: Create network interface for each gre endpoint
  notify: Restart networkd
  template:
    src: gre-network.j2
    dest: /etc/systemd/network/10-gre-{{ item.key }}.network
  with_dict: "{{ supernodes }}"

- name: Create /etc/systemd/network/10-eth0.network.d directory
  notify: Restart networkd
  file:
    name: /etc/systemd/network/10-eth0.network.d  
    state: directory

- name: Drop tunnel config into /etc/systemd/network/10-eth0.network.d directory
  notify: Restart networkd
  template: 
    src: tunnel.conf.j2
    dest: /etc/systemd/network/10-eth0.network.d/gre-tunnel.conf

- name: Create gre tunnel in networkd
  notify: Restart networkd
  template:
    src: gre-netdev.j2
    dest: /etc/systemd/network/20-gre-{{ item.key }}.netdev
  with_dict: "{{ supernodes }}"

