TODO: WORK IN PROGRESS - FINISH WORK, THEN TEST
---

- name: Kernel modules stuff
  include_tasks: kmod.yml

- name: Firewall stuff
  include_tasks: ferm.yml

- name: sysctl stuff
  include_tasks: sysctl.yml
