---

- name: Add universe-factory repository key
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: CB201D9CCB201D9C

- name: Add universe-factory repositories
  apt_repository:
    repo: "deb http://repo.universe-factory.net/debian/ sid main"
    update_cache: yes

- name: Install fastd
  apt: name=fastd

- name: Remove autostart of generic fastd instance on boot
  service: name=fastd enabled=no

- name: Create fastd_mesh daemon config directories
  file: path=/etc/fastd/fastd_mesh state=directory

- name: Install fastd_mesh daemon config
  notify: Restart fastd_mesh
  template:
    dest: "/etc/fastd/fastd_mesh/fastd.conf"
    src: "fastd.conf.j2"

- name: Install fastd_mesh daemon secret
  notify: Restart fastd_mesh
  template:
    dest: "/etc/fastd/fastd_mesh/secret.conf"
    src: "secret.conf.j2"
    mode: "u=rw,g=,o="

- name: Create fastd_mesh remotes file
  file:
    path: "/etc/fastd/fastd_mesh/remotes.conf"
    state: touch
  notify: Restart fastd_mesh

- name: Start fastd_mesh on boot
  service: name=fastd@fastd_mesh enabled=yes

- name: Install fastd_mesh iface config
  notify: Reload fastd_mesh iface config
  template:
    dest: "/etc/network/interfaces.d/40_fastd_mesh.cfg"
    src: "fastd_mesh_iface.cfg.j2"
