---

- name: Install https for apt
  apt:
    update_cache: yes
    name: apt-transport-https

- name: Add universe-factory repository key
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: CB201D9CCB201D9C

- name: Add universe-factory repositories
  apt_repository:
    repo: "deb http://repo.universe-factory.net/debian/ sid main"

- name: Install fastd
  apt: name=fastd update_cache=yes

- name: Remove autostart of generic fastd instance on boot
  service: name=fastd enabled=no

- name: Create fastd_mesh daemon config directories
  file: path=/etc/fastd/fastd_mesh state=directory

- name: Install fastd_mesh daemon config
  notify: Restart fastd_mesh
  template:
    dest: "/etc/fastd/fastd_mesh/fastd.conf"
    src: "fastd.conf.j2"

- name: Install fastd_mesh daemon secret
  notify: Restart fastd_mesh
  template:
    dest: "/etc/fastd/fastd_mesh/secret.conf"
    src: "secret.conf.j2"
    mode: "u=rw,g=,o="

- name: Check if fastd_mesh remotes file exists
  stat: path=/etc/fastd/fastd_mesh/remotes.conf
  register: remotes

- name: Ensure fastd_mesh remotes file exits
  when: not remotes.stat.exists
  file: path=/etc/fastd/fastd_mesh/remotes.conf state=touch
  notify: Restart fastd_mesh

- name: Start fastd_mesh on boot
  service: name=fastd@fastd_mesh enabled=yes state=started
