---

- name: Add Zabbix Repo Key
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present
    keyring: /etc/apt/trusted.gpg.d/zabbix.gpg

- name: Add Zabbix Repo
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/4.0/debian stretch main"
    state: present
    filename: zabbix

- name: Install zabbix-agent via apt
  apt:
    name: zabbix-agent
    update_cache: yes

- name: Open zabbix-agent port in firewall (ferm)
  notify: reload ferm
  template:
    src: ferm.conf.j2
    dest: "/etc/ferm/conf.d/50-zabbix-agent.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Deploy zabbix-agent config file
  notify: reload zabbix-agent
  template:
    src: agent.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.d/ansible.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Enable and start zabbix-agent
  systemd:
    name: "zabbix-agent"
    enabled: yes
    state: "started"
