---

- name: Create iperf user
  register: createuser
  user:
    name: iperf
    shell: /sbin/nologin

- name: Generate systemd unit file for iperf
  template:
    src: iperf3.service.j2
    dest: /etc/systemd/system/iperf3.service

- name: Install iperf3
  apt: name=iperf3

- name: Start iperf3 daemon on boot
  service: name=iperf3 enabled=yes state=started

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-iperf3.conf
  notify: reload ferm

- name: Restart ferm
  service: name=ferm state=restarted
  when: ferm_changed | changed



