---

- name: Create iperf user
  register: createuser
  user:
    name: iperf
    shell: /sbin/nologin

- name: Generate custom gen_stats.sh script
  template:
    src: iperf.service.j2
    dest: /etc/systemd/system/iperf.service

- name: Install iperf3
  apt: name=iperf3

- name: Start iperf3 daemon on boot
  service: name=iperf enabled=yes state=started
