---
firewall_ssh_ports: [22]
firewall_open_ports_tcp: []
firewall_open_ports_tcp_by_iface: []
firewall_open_ports_udp: []
firewall_open_ports_udp_by_iface: []
firewall_allowed_forwards: []
firewall_nat4_on_interfaces: []
firewall_alternative_routingtables: []
# -1 means the default value of "nf_conntrack_buckets value * 4"
firewall_conntrack_table_size: -1
firewall_dnat4: []
firewall_open_ports_udp_by_ip: []
firewall_open_ports_tcp_by_ip: []
