---

- name: Uninstall OS-shipped radvd
  apt: name=radvd state=absent

- name: Install build-essential
  apt:
    pkg:
    - build-essential
    - bison
    - flex

- name: Unarchive radvd to local directory
  unarchive:
    src: "http://www.litech.org/radvd/dist/radvd-2.18.tar.gz"
    dest: "/usr/src"
    owner: "root"
    group: "root"
    remote_src: yes

- name: Configure
  command: "./configure --prefix=/usr/local --sysconfdir=/etc --mandir=/usr/share/man"
  args:
    chdir: "/usr/src/radvd-2.18"

- name: Make
  make:
    chdir: "/usr/src/radvd-2.18"

- name: Make install
  make:
    chdir: "/usr/src/radvd-2.18"
    target: "install"

- name: Generate radvd config
  notify: Restart radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf

- name: Add systemd service file
  template:
    src: systemd.service
    dest: /etc/systemd/system/radvd.service

- name: Enable radvd
  command: systemctl enable radvd

- name: Start radvd
  command: systemctl start radvd
