---

- name: Enable backbone remotes
  lineinfile:
    dest: /etc/fastd/fastd_mesh/remotes.conf
    line: "include \"backbone.conf\";"

- name: Install backbone remotes file
  notify: Restart fastd_mesh
  template:
    dest: "/etc/fastd/fastd_mesh/backbone.conf"
    src: "backbone.conf.j2"
