---
dns_authoritative_toplevel:
   - domain: "ffh.zone."
     records: [
       "sn01.ffh.zone. IN CNAME sn01.s.ffh.zone.",
       "sn02.ffh.zone. IN CNAME sn02.s.ffh.zone.",
       "sn03.ffh.zone. IN CNAME sn03.s.ffh.zone.",
       "sn04.ffh.zone. IN CNAME sn04.s.ffh.zone.",
       "sn05.ffh.zone. IN CNAME sn05.s.ffh.zone.",
       "sn06.ffh.zone. IN CNAME sn06.s.ffh.zone.",
       "sn07.ffh.zone. IN CNAME sn07.s.ffh.zone.",
       "sn08.ffh.zone. IN CNAME sn08.s.ffh.zone.",
       "sn09.ffh.zone. IN CNAME sn09.s.ffh.zone.",
       "sn10.ffh.zone. IN CNAME sn10.s.ffh.zone.",
       "sn01.maint.ffh.zone. 120 IN A 194.50.19.35",
       "sn01.maint.ffh.zone. IN AAAA 2a07:59c6:eefd:5::1001",
       "sn01.s.ffh.zone. 120 IN A 185.197.132.140",
       # "sn02.s.ffh.zone. IN A 195.201.97.8",
       # "sn02.s.ffh.zone. IN AAAA 2a01:4f8:1c0c:7149::2001",
       "sn03.s.ffh.zone. IN A 51.38.107.247",
       # "sn03.s.ffh.zone. IN AAAA 2001:4ba0:babe:3054::3001",
       # "sn04.s.ffh.zone. IN A 195.201.136.197",
       # "sn04.s.ffh.zone. IN AAAA 2a01:4f8:1c1c:10fe::4001",
       # "sn05.s.ffh.zone. IN A 116.203.68.28",
       # "sn05.s.ffh.zone. IN AAAA 2a01:4f8:1c1c:ce20::5001",
       # "sn06.s.ffh.zone. IN A 173.249.5.34",
       # "sn06.s.ffh.zone. IN AAAA 2a02:c207:3002:3831::6001",
       # "sn07.s.ffh.zone. IN AAAA 2a02:c207:3003:6341::1",
       # "sn07.s.ffh.zone. IN A 173.212.239.89",
       "sn08.s.ffh.zone. IN A 176.9.100.184",
       "sn08.s.ffh.zone. IN AAAA 2a01:4f8:151:42a1::8001",
       "sn08-host.ffh.zone. IN A 176.9.100.177",
       "sn09.s.ffh.zone. IN A 81.3.6.92",
       "sn09.s.ffh.zone. IN AAAA 2a02:790:1:ff::9001",
       "sn10.s.ffh.zone. IN A 81.3.6.91",
       "sn10.s.ffh.zone. IN AAAA 2a02:790:1:ff::a001",
       # "steintor.e.ffh.zone. IN A 37.120.190.215",
       # "steintor.e.ffh.zone. IN AAAA 2a03:4000:6:b1d6::1",
       "leintor.e.ffh.zone. IN AAAA 2a02:790:1:ff::1001",
       "leintor.e.ffh.zone. IN A 81.3.6.94",
       # "clevertor.e.ffh.zone. IN AAAA 2a02:c207:3002:4406::1",
       # "clevertor.e.ffh.zone. IN A 173.249.22.70",
       # "bruehltor.e.ffh.zone. IN A 213.136.89.119",
       # "bruehltor.e.ffh.zone. IN AAAA 2a02:c207:3003:7339::1",
       # "aegidientor.e.ffh.zone. 60 IN A 88.198.67.124",
       # "aegidientor.e.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a::ff",
       # "listertor.e.ffh.zone. IN AAAA 2a02:c207:3003:6341::1",
       # "listertor.e.ffh.zone. IN A 173.212.239.89",
       "pve-ffnw.ffh.zone. IN A 194.50.19.34",
       "pve-ffnw.ffh.zone. IN AAAA 2a07:59c6:eefd:5::1",
       "monitor.ffh.zone. IN A 88.99.100.14",
       "monitor.ffh.zone. IN AAAA 2a01:4f8:221:100c::1003",
       "zabbix.ffh.zone. IN CNAME monitor.ffh.zone.",
       "netbox.ffh.zone. IN CNAME monitor.ffh.zone.",
       "ntp.ffh.zone. IN A 37.120.176.252",
       "ntp.ffh.zone. IN AAAA 2a03:4000:6:8277::1",
       "web.ffh.zone. 60 IN A 88.198.66.3",
       "web.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a:ff::443",
       "tiles.ffh.zone. IN CNAME web.ffh.zone.",
       "stats.ffh.zone. 60 IN A 88.198.66.29",
       "stats.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a::101",
       "prometheus.ffh.zone. IN CNAME stats.ffh.zone.",
       "babelnetz.ffh.zone. IN NS nsbabel.fnorden.net.",
       "harvester.ffh.zone. 60 IN A 88.198.66.29",
       "harvester.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a::101",
       "webdebug.ffh.zone. IN A 10.2.80.1",
       "observer.ffh.zone. IN A 37.120.178.19",
       "observer.ffh.zone. IN AAAA 2a03:4000:6:82c8::1",
       "observer.ffh.zone. IN MX 1 observer.ffh.zone.",
       "observer.ffh.zone. IN TXT \"v=spf1 a mx ~all\"",
       "git.ffh.zone. IN A 37.120.176.252",
       "git.ffh.zone. IN AAAA 2a03:4000:6:8277::1",
       "firmware.ffh.zone. 60 IN A 88.198.66.3",
       "firmware.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a:ff::443",
       "mail.ffh.zone. IN A 37.120.176.252",
       "mail.ffh.zone. IN AAAA 2a03:4000:6:8277::1",
       "build.ffh.zone. IN AAAA 2001:470:775a:42:1000::115",
       "build.ffh.zone. IN A 130.75.178.26",
       "lounge.ffh.zone. IN AAAA 2001:470:775a:42:1000::115",
       "lounge.ffh.zone. IN A 130.75.178.26",
       "opkg.ffh.zone. 60 IN AAAA 2a01:4f8:140:430a::101",
       "nrue.ffh.zone. IN NS freedns1.registrar-servers.com."
     ]

dns_authoritative_zones:
# - zone: "firmware"
#   to: "fdca:ffee:8::102"
- zone: "hightower"
  to: "fdca:ffee:8::1337"
