---
servername: sn03
sn: 3
mail_fqdn: "sn03.s.ffh.zone"
admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush, codefetch, DarkAMD]

networkd_configures:
- iface: eth0
  addresses:
    - 51.38.107.247/24
  gateway4: 51.38.107.254
  no_radv_accept: true
  dns_server: [8.8.8.8]

babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor', 'gre-aegidientor', 'gre-bruehltor']
babeld_interface_penalty:
  gre-aegidientor: 666
  gre-steintor: 130
  gre-leintor: 110
  gre-clevertor: 100
  gre-listertor: 120
  gre-bruehltor: 666

legacy_dom0: true
radv_announce_default: false
