---
servername: sn06
sn: 6
mail_fqdn: "sn06.s.ffh.zone"

networkd_configures:
- iface: eth0
  addresses:
    - 173.249.5.34/24
    - 2a02:c207:3002:3831::6001/64
  gateway4: 173.249.5.1
  gateway6: fe80::1
  no_radv_accept: true
  dns_server: [213.136.95.10, 213.136.95.11]

babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor', 'gre-aegidientor', 'gre-bruehltor']
babeld_interface_penalty:
  gre-aegidientor: 666
  gre-steintor: 130
  gre-leintor: 110
  gre-clevertor: 100
  gre-listertor: 120
  gre-bruehltor: 666

legacy_dom0: true
radv_announce_default: false
