---
servername: sn08
sn: 8
mail_fqdn: "sn08.s.ffh.zone"

networkd_configures:
- iface: eth0
  addresses:
    - 2a01:4f8:151:42a1::8001/64
  gateway6: 2a01:4f8:151:42a1::2
  no_radv_accept: true
  dhcp: true
  dns_server: [9.9.9.9, 1.1.1.1]

babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor', 'gre-aegidientor', 'gre-bruehltor']
babeld_interface_penalty:
  gre-aegidientor: 666
  gre-steintor: 120
  gre-leintor: 130
  gre-clevertor: 110
  gre-listertor: 100
  gre-bruehltor: 666

legacy_dom0: true
radv_announce_default: false
