---
servername: sn09
sn: 9
mail_fqdn: "sn09.s.ffh.zone"
admin_authorized: [lemoer, cawi, luk, manawyrm, aiyion, jue, okrueger, raute, tobby, sush, codefetch, DarkAMD]

networkd_configures:
- iface: eth0
  addresses:
    - 81.3.6.92/29
    - 2a02:790:1:ff::9001/64
  gateway4: 81.3.6.89
  gateway6: fe80::1
  no_radv_accept: true
  dns_server: [81.3.3.81, 83.246.106.204]

babeld_interfaces: ['gre-steintor', 'gre-leintor', 'gre-clevertor', 'gre-listertor', 'gre-aegidientor', 'gre-bruehltor']
babeld_interface_penalty:
  gre-aegidientor: 666
  gre-steintor: 130
  gre-leintor: 100
  gre-clevertor: 120
  gre-listertor: 110
  gre-bruehltor: 666

legacy_dom0: true
radv_announce_default: true
