---

- name: Ensure git
  apt:
    name: git
    update_cache: yes

- name: Ensure ansible dir
  file:
      dest: /var/lib/ansible
      state: directory

- name: Check installed go version
  register: goversion
  copy:
    content: "{{ go_version }}"
    dest: /var/lib/ansible/go_version

- name: Download and install go
  unarchive:
    src: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: True
  when: goversion|changed

- name: Install path to go stuff
  copy:
    content: |
      export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
      export GOPATH=/opt/go
    dest: /etc/profile.d/go.sh
    mode: 755

# TODO: install yanic

- name: Create yanic user
  user:
    name: "{{ yanic_user }}"
    group: "{{ yanic_group }}"
    system: yes

- name: Ensure persist directory, if needed
  file:
    path: "/var/lib/yanic/"
    state: directory
    owner: yanic
  when: yanic_nodes_enabled

- name: Ensure nodes path, if needed
  file:
    path: "{{ yanic_nodes_path }}"
    state: directory
    owner: yanic
  when: yanic_nodes_enabled

- name: Configure yanic
  notify: Restart yanic
  template:
    src: config.yml.j2
    dest: /etc/yanic.conf

- name: Copy systemd service
  template:
    src: yanic.service.j2
    dest: /lib/systemd/system/yanic.service

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-yanic.conf
  notify: reload ferm

- name: Enable yanic
  systemd:
    name: yanic
    state: started
    enabled: yes
