---

- name: Install batctl
  apt: name=batctl

- name: Install autostart batman_adv on boot
  lineinfile: dest=/etc/modules line=batman_adv

- name: Load batman_adv module
  modprobe: name=batman_adv state=present

- name: Install bat0 network config
  notify: Restart networkd
  template: src=30-batman.network.j2 dest=/etc/systemd/network/30-batman.network
