---

- name: Install iptables-persistent
  apt: name=iptables-persistent

- name: Install nf_conntrack kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack

- name: Install nf_conntrack_ipv4 kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack_ipv4

- name: Install nf_conntrack_ipv6 kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack_ipv6

- name: Adjust netfilter conntrack table size
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "{{ firewall_conntrack_table_size }}"
    state: "{% if firewall_conntrack_table_size != -1 %}present{% else %}absent{% endif %}"
    sysctl_file: /etc/sysctl.d/20-conntrack.conf
    reload: yes

- name: Maybe activate forwarding 4 as kernel parameter
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "{% if firewall_allowed_forwards|length > 0 or firewall_dnat4|length > 0 %} 1 {% else %} 0 {% endif %}"
    sysctl_file: /etc/sysctl.d/50-forwarding.conf
    reload: yes

- name: Maybe activate forwarding 6 as kernel parameter
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "{% if firewall_allowed_forwards|length > 0 %} 1 {% else %} 0 {% endif %}"
    sysctl_file: /etc/sysctl.d/50-forwarding.conf
    reload: yes

- name: Generate test config iptables v4 config
  register: iptables4
  template:
    dest: "/etc/iptables/rules.v4"
    src: "iptables4.j2"
    validate: "iptables-restore --test %s"

- name: Generate test config iptables v6 config
  register: iptables6
  template:
    dest: "/etc/iptables/rules.v6"
    src: "iptables6.j2"
    validate: "ip6tables-restore --test %s"

- name: Load and apply the new firewall 4 rules
  command: iptables-restore /etc/iptables/rules.v4
  when: iptables4|changed

- name: Load and apply the new firewall 6 rules
  command: ip6tables-restore /etc/iptables/rules.v6
  when: iptables6|changed

- name: Ensure alternative routing tables are existing
  lineinfile:
    dest: /etc/iproute2/rt_tables
    line: "{{ 42 + item.0 }} {{ item.1.name }}"
    # routing table numbers begin at number 42
  with_indexed_items: "{{ firewall_alternative_routingtables }}"

- name: Deploy /etc/rc.local
  register: rclocal
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    mode: u=rwx,g=rx,o=rx

- name: Apply changes in /etc/rc.local
  command: /etc/rc.local
  when: rclocal|changed

- name: Generate script for alternative routingtables
  template:
    src: alternative_routingtables.sh.j2
    dest: /usr/bin/alternative_routingtables.sh
    mode: u=rwx,g=rx,o=rx

- name: Activate cronjob to watch alternative_routingtables
  cron:
    name: "watch alternative_routingtables"
    user: root
    minute: "*"
    job: /usr/bin/alternative_routingtables.sh
