---

- hosts: supernodes
  roles:
    # General
    - { name: ffh.devname, tags: devname }
    - { name: ffh.ferm, tags: ferm }
    - { name: ffh.supernode, tags: supernode }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.networkd, tags: networkd }
    - { name: ffh.babeld, tags: babeld }
    - { name: ffh.simple_mail, tags: simple_mail }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cron-apt, tags: cron-apt }
    # Batman
    - { name: ffh.mesh_batman, tags: mesh_batman }
    - { name: ffh.mesh_fastd, tags: mesh_fastd }
    - { name: ffh.mesh_fastd_remotes_peers_git, tags: mesh_fastd_remotes_peers_git }
    - { name: ffh.mesh_announce, tags: mesh_announce }
    # Stats, Monitoring, Logging
    - { name: ffh.radv_server, tags: radv_server }
    - { name: ffh.dns_recursive, tags: dns_recursive }
    - { name: ffh.dhcp_server, tags: dhcp_server }
    - { name: ffh.gateway_announcement, tags: gateway_announcement }
    - { name: ffh.iperf3, tags: iperf3 }
    - { name: ffh.journald, tags: journald }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: ffh.apinger, tags: apinger }
    - { name: ffh.telegraf, tags: telegraf }
    - { name: ffh.promtail, tags: promtail }
    - { name: ffh.routingnode, tags: routingnode }

  vars_files:
    - ../secrets.yml


- hosts: sn01
  roles:
    - { name: ffh.superexitnode, tags: superexitnode }
