---

- name: Install babeld
  apt: name=babeld

- name: Install babeld supernode config
  notify: Restart babeld
  template:
    src: supernode.conf.j2
    dest: /etc/babeld.conf
  when: babeld_supernode | default(False)

- name: Install babeld systemd service
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/babeld.service

- name: Enable service
  systemd:
    name: babeld
    state: restarted
    enabled: yes
    daemon_reload: yes

