---

- name: Install babeld
  apt: name=babeld

- name: Install babeld supernode config
  notify: Restart babeld
  template:
    src: supernode.conf.j2
    dest: /etc/babeld.conf
  when: babeld_supernode | default(False)

- name: Install babeld exitnode config
  notify: Restart babeld
  template:
    src: exitnode.conf.j2
    dest: /etc/babeld.conf
  when: babeld_exitnode | default(False)

- name: Install babeld systemd service
  notify: Restart babeld
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/babeld.service
  when: ansible_service_mgr == 'systemd'

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-babeld.conf
  notify: reload ferm

- name: Start service
  systemd:
    name: babeld
    state: started
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: Start service
  service:
    name: babeld
    state: started
  when: ansible_service_mgr != 'systemd'

- name: install /etc/default
  notify: Restart babeld with service
  template:
    src: default.j2
    dest: /etc/default/babeld
  when: ansible_service_mgr != 'systemd'

- name: Enable service
  service:
    name: babeld
    enabled: yes

