---

- name: Enable dom0 backbone config
  include_tasks: dom0.yml
  when: legacy_dom0 == true

- name: Domain configs
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined
