---

- name: Enable systemd-networkd
  service: name=systemd-networkd enabled=yes state=started

- name: Enable systemd-resolved
  service: name=systemd-resolved enabled=yes state=started

- name: Disable debian networking
  service: name=networking enabled=no state=stopped

- name: Enable dns resolving with systemd-resolved
  file: src=/run/systemd/resolve/resolv.conf dest=/etc/resolv.conf state=link force=yes

- name: Install uplink iface config
  notify: Restart networkd
  template: src=10-uplink.network.j2 dest=/etc/systemd/network/10-uplink.network
