---

- name: Install cli tools
  apt: name={{ item }}
  with_items:
    - netcat-openbsd
    - tcpdump
    - nmap
    - mtr-tiny
    - iperf3
    - iftop
    - htop
    - dstat
    - iotop
    - vim
    - screen
    - tmux
    - byobu
    - conntrack
