---

- name: Install cli tools
  apt: name={{ item }} update_cache=yes
  with_items:
    - netcat-openbsd
    - tcpdump
    - nmap
    - mtr-tiny
    - iftop
    - htop
    - dstat
    - iotop
    - vim
    - screen
    - tmux
    - byobu
    - conntrack
    - bash-completion
    - psmisc
    - curl
    - mosh
    - iputils-tracepath
    - jq
    - net-tools

- name: Deploy fastd_connected
  template:
    src: fastd_connected.j2
    dest: /usr/local/bin/fastd_connected
    mode: 0755

- name: Set prompt (PS1)
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\e[37m\][\[\e[m\]\[\e[32m\]\u\[\e[m\]\[\e[37m\]@\[\e[m\]\[\e[31m\]{{ servername or "\h" }}\[\e[m\]\[\e[37m\]]\[\e[m\]\[\e[37m\]:\[\e[m\]\[\e[34m\]\w\[\e[m\] \[\e[37m\]\\$\[\e[m\] "'

- name: Set dr alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias dr="ip r s t 0 | grep \"default via\" && ip -6 r s t 0 | grep \"default via\""'

