---

- name: Install cli tools
  apt: name={{ item }}
  with_items:
    - netcat-openbsd
    - tcpdump
    - nmap
    - mtr-tiny
    - iftop
    - htop
    - dstat
    - iotop
    - vim
    - screen
    - tmux
    - byobu
    - conntrack
    - bash-completion
    - psmisc
    - curl

- name: Deploy fastd_connected
  template:
    src: fastd_connected.j2
    dest: /usr/local/bin/fastd_connected
    mode: 0755
