---

- name: Install cli tools
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - netcat-openbsd
    - tcpdump
    - nmap
    - mtr-tiny
    - iftop
    - htop
    - dstat
    - iotop
    - vim
    - screen
    - tmux
    - byobu
    - conntrack
    - bash-completion
    - psmisc
    - curl
    - mosh
    - iputils-tracepath
    - jq
    - net-tools
    - dnsutils
    - ndisc6

- name: Set prompt (PS1)
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\e[37m\][\[\e[m\]\[\e[32m\]\u\[\e[m\]\[\e[37m\]@\[\e[m\]\[\e[31m\]{{ servername | default("\h") }}\[\e[m\]\[\e[37m\]]\[\e[m\]\[\e[37m\]:\[\e[m\]\[\e[34m\]\w\[\e[m\] \[\e[37m\]\\$\[\e[m\] "'

- name: Set dr alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias dr="ip r s t 0 | grep \"default via\" && ip -6 r s t 0 | grep \"default via\""'

- name: Set traceraute alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias traceraute="traceroute"'
